### ISSUE TITLE
GameMe Support

### ISSUE THREAD

**Issue by lazhoroni** [diogooonair/CSGO---MatchMaking-ranks-with-rankme-support-and-prestige#2]
Do you add gameme support?
https://github.com/hallucinogenic/MatchMaking-Ranks-By-Points 
This add-on is available but the ranks are not updated every time the round starts. To be able to use only fakerank: can you add all of the settings commands that we can deactivate?

**Comment by diogooonair** [comment]
All avaible cvars are in alliedmodders thread. No it don t have gameme  support for now just rankme but i can add it later

**Comment by lazhoroni** [comment]
ranks are updated when map changes in this plugin. points change immediately when the round starts or does not change. If you do compatible with gameme, you will use your plugin.

**Comment by lazhoroni** [comment]
sm_ranksbyrankme_mode Will the reward be disabled when I set the value to 0?

**Comment by diogooonair** [comment]
Yes
