### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by Dazzah2** [diogooonair/CSGO---MatchMaking-ranks-with-rankme-support-and-prestige#3]
No matter what i try no Unapproved plugins are working ive got all the settings correct in core.cfg but yet no matter what they wont work, This wont nor will weapon skins etc

**Comment by diogooonair** [comment]
Add me on steam
´https://steamcommunity.com/id/diogo218dv

**Comment by diogooonair** [comment]
Remaking it at the moment if you want to request any new freature feel free!

**Comment by diogooonair** [comment]
All fixed on new version!
