### ISSUE TITLE
database problem

### ISSUE THREAD

**Issue by csgentr** [diogooonair/CSGO---MatchMaking-ranks-with-rankme-support-and-prestige#4]
L 08/08/2019 - 03:15:49: SourceMod error session started
L 08/08/2019 - 03:15:49: Info (map "de_dust2") (file "errors_20190808.log")
L 08/08/2019 - 03:15:49: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 08/08/2019 - 03:15:49: [SM] Blaming: ranksforrankme.smx
L 08/08/2019 - 03:15:49: [SM] Call stack trace:
L 08/08/2019 - 03:15:49: [SM]   [0] Database.Format
L 08/08/2019 - 03:15:49: [SM]   [1] Line 90, C:\Users\diogo\OneDrive\Ambiente de Trabalho\Prestige - Ranks For Rankme\scripting\ranksforrankme.sp::OnPluginStart
L 08/08/2019 - 03:15:49: [SM] Unable to load plugin "ranksforrankme.smx": Error detected in plugin startup (see error logs)

there is error, I use to kento rankme plugin. can u help me ;?

**Comment by diogooonair** [comment]
Look at the server logs.
Probably the database data is wrong at databases.cfg or the server ip is not allowed into the database hosting

**Comment by diogooonair** [comment]
Remaking it at the moment if you want to request any new freature feel free!

**Comment by diogooonair** [comment]
All fixed on new version!

**Comment by csgentr** [comment]
thanks but I want to give a VIP permission when they get reach prestige rank. for 1 week or 2 week. with aop flags..

**Comment by diogooonair** [comment]
Disabled that temporarly for optimization, probably tommorow will lauch a version with it already!
