### ISSUE TITLE
Problem with !mm

### ISSUE THREAD

**Issue by ghost** [diogooonair/CSGO---MatchMaking-ranks-with-rankme-support-and-prestige#5]
Hy bro, when I type !mm on my server nothing happens, and I had this plugin installed before, and when I wrote !mm only shows me the rank until legendary eagle! And this happens in others servers! 

Ps- I tryed to compile your plugin from my computer but said "cant read from HLSX_Stat_API and I download this file and now said 
// ranks_matchmaking.sp(237) : error 100: function prototypes do not match
// ranks_matchmaking.sp(322) : error 100: function prototypes do not match

so maybe the plugin has some problem

**Comment by diogooonair** [comment]
Remaking it at the moment if you want to request any new freature feel free!

**Comment by diogooonair** [comment]
All fixed on new version!
